# Generated by Django 4.2.11 on 2025-03-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotmentapp', '0005_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=999999999, max_length=15),
        ),
    ]
