# Generated by Django 4.2.11 on 2025-04-25 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allotmentapp', '0007_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='AllocationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('department_quota_percentage', models.PositiveIntegerField(default=20, help_text='Percentage of department strength to allocate as MDC quota', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('general_quota_percentage', models.PositiveIntegerField(default=60, help_text='Percentage for General category', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sc_st_quota_percentage', models.PositiveIntegerField(default=20, help_text='Percentage for SC/ST category', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('other_quota_percentage', models.PositiveIntegerField(default=20, help_text='Percentage for EWS/Sports/Management category', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotmentapp.department')),
            ],
            options={
                'verbose_name': 'Allocation Setting',
                'verbose_name_plural': 'Allocation Settings',
            },
        ),
    ]
