# Generated by Django 4.2.11 on 2025-04-25 10:45

from django.db import migrations

def create_initial_settings(apps, schema_editor):
    # Get models
    Department = apps.get_model('allotmentapp', 'Department')
    AllocationSettings = apps.get_model('allotmentapp', 'AllocationSettings')
    
    # Create settings for each department
    departments = Department.objects.all()
    
    for dept in departments:
        # Set default values based on department type if needed
        default_strength = {
            'Economics': 48,
            'History': 48,
            'Malayalam': 36,
            'Commerce': 55,
            'Physics': 43,
            'Chemistry': 29,
            'Zoology': 29,
            'Botany': 29,
            'Statistics': 29
        }.get(dept.name, 30)  # Default to 30 if department not in list
        
        AllocationSettings.objects.create(
            department=dept,
            strength=default_strength,
            department_quota_percentage=20,
            general_quota_percentage=60,
            sc_st_quota_percentage=20,
            other_quota_percentage=20
        )

def reverse_migration(apps, schema_editor):
    AllocationSettings = apps.get_model('allotmentapp', 'AllocationSettings')
    AllocationSettings.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('allotmentapp', '0008_alter_student_admission_year_and_more'),  # Replace with your last migration
    ]

    operations = [
        migrations.RunPython(create_initial_settings, reverse_migration),
    ]