# Generated by Django 4.2.11 on 2025-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotmentapp', '0008_alter_student_admission_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='isMajor',
            field=models.BooleanField(default=False),
        ),
    ]
