# Generated by Django 4.2.11 on 2025-04-25 13:58

from django.db import migrations

def create_initial_settings(apps, schema_editor):
    # Get models
    Department = apps.get_model('allotmentapp', 'Department')
    AllocationSettings = apps.get_model('allotmentapp', 'AllocationSettings')
    
    # Only select major departments
    departments = Department.objects.filter(isMajor=True)
    
    # Default strength mapping
    default_strength_map = {
        'Economics': 48,
        'History': 48,
        'Malayalam': 36,
        'Commerce': 55,
        'Physics': 43,
        'Chemistry': 29,
        'Zoology': 29,
        'Botany': 29,
        'Statistics': 29
    }
    
    for dept in departments:
        default_strength = default_strength_map.get(dept.name, 30)  # Fallback to 30 if not listed

        AllocationSettings.objects.create(
            department=dept,
            strength=default_strength,
            department_quota_percentage=20,
            general_quota_percentage=60,
            sc_st_quota_percentage=20,
            other_quota_percentage=20
        )

def reverse_migration(apps, schema_editor):
    AllocationSettings = apps.get_model('allotmentapp', 'AllocationSettings')
    AllocationSettings.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('allotmentapp', '0009_department_ismajor'),  # Replace if needed
    ]

    operations = [
        migrations.RunPython(create_initial_settings, reverse_migration),
    ]
