# Generated by Django 4.2.11 on 2025-07-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allotmentapp', '0009_department_ismajor_alter_batch_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-year', 'part', 'course__course_code'], 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='seats_taken',
            field=models.PositiveIntegerField(default=0, help_text='Number of seats already allocated'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='allotmentapp.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='part',
            field=models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2')], default=1),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.BooleanField(default=True, help_text='Whether this batch is active for allocations'),
        ),
    ]
