# Generated by Django 4.2.11 on 2025-07-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotmentapp', '0011_swaphistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwapHistory',
        ),
    ]
