# Generated by Django 4.2.11 on 2025-07-27 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotmentapp', '0012_delete_swaphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_sem_marks',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='normalized_marks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
