from django.urls import path
from allotmentapp import views

urlpatterns = [
    path('', views.index, name='home'),
    path("admin-login/", views.admin_login, name="admin_login"),
    path("student-login/",views.student_login, name="student_login"),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    # path('add-student/', views.add_student, name='add_student'),
    path('student-dashboard/', views.student_dashboard, name='student_dashboard'),
    path("view_courses_std/", views.view_courses_student, name="view_courses_student"),
    path('course_selection/',views.course_selection, name='course_selection'),
    path('view_preferences/', views.view_preferences, name='view_preferences'),
    path('edit_preferences/', views.edit_preferences, name='edit_preferences'),

    path('logout/',views.student_logout, name='logout'),
    path('logout/',views.admin_logout, name='admin_logout'),
    path('add_course/', views.add_course, name='add_course'),
    path('manage_courses/', views.manage_courses, name='manage_courses'), 
    path('edit_course/<int:course_id>/', views.edit_course, name='edit_course'),
    path('delete_course/<int:course_id>/', views.delete_course, name='delete_course'),
    path('manage_courses/', views.manage_courses, name='manage_courses'),
    path('manage_batches/', views.manage_batches, name='manage_batches'),
    path('create_batch/', views.create_batch, name='create_batch'),
    path('edit_batch/<int:batch_id>/', views.edit_batch, name='edit_batch'),
    path('delete_batch/<int:batch_id>/', views.delete_batch, name='delete_batch'),
     path('manage_allotment/', views.manage_allotment, name='manage_allotment'),
    path('first_sem_allotment/', views.first_sem_allotment, name='first_sem_allotment'),
    path('second_sem_allotment/', views.second_sem_allotment, name='second_sem_allotment'),
    path('view_first_sem_allotments/', views.view_first_sem_allotments, name='view_first_sem_allotments'),
    path('view_second_sem_allotments/', views.view_second_sem_allotments, name='view_second_sem_allotments'),

    path('view-allotment/', views.view_student_allotment, name='view_student_allotment'),
    
    path('manage_students/', views.manage_students, name='manage_students'),
    path('register/', views.student_register, name='student_register'),
    path("bulk-upload/", views.bulk_student_upload, name="bulk_student_upload"),
    path('students/<int:student_id>/', views.student_detail, name='student_detail'),
    path('students/<int:student_id>/edit/', views.student_edit, name='student_edit'),
    path('students/<int:student_id>/delete/', views.student_delete, name='student_delete'),
    path('download_preferences_csv_first_sem/', views.download_preferences_csv_first_sem, name='download_preferences_csv_first_sem'),
    path('download_preferences_csv_second_sem/', views.download_preferences_csv_second_sem, name='download_preferences_csv_second_sem'),
    path('hod_list/', views.hod_list, name='hod_list'),
    path('hods/<int:hod_id>/edit/', views.hod_edit, name='hod_edit'),
    path('hods/<int:hod_id>/delete/', views.hod_delete, name='hod_delete'),
    path('add-hod/', views.add_hod, name='add_hod'),

    path("hod-login/", views.hod_login, name="hod_login"),
    path("hod-logout/", views.hod_logout, name="hod_logout"),
    path("hod-dashboard/", views.hod_dashboard, name="hod_dashboard"),

    path("hod-dashboard/", views.hod_dashboard, name="hod_dashboard"),
    path("hod-profile/", views.hod_profile, name="hod_profile"),
    path('hod/students/', views.hod_student_list, name='hod_student_list'),
    path('hod/students/<int:student_id>/', views.hod_student_detail, name='hod_student_detail'),
    path('hod/students/<int:student_id>/edit/', views.hod_student_edit, name='hod_student_edit'),
    path('students/delete/<int:student_id>/',views.hod_student_delete, name='hod_student_delete'),
]
