# Generated by Django 4.2.11 on 2025-02-06 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('part', models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2')])),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admission_category', models.CharField(choices=[('General', 'General'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('PWD', 'Persons with Disability'), ('EWS', 'Economically Weaker Section'), ('Sports', 'Sports Quota'), ('Management', 'Management Quota')], default='General', max_length=20)),
                ('current_sem', models.PositiveIntegerField(default=1)),
                ('normalized_marks', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotmentapp.department')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotmentapp.pathway')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_number', models.PositiveIntegerField()),
                ('paper_no', models.PositiveIntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotmentapp.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotmentapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotmentapp.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotmentapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=15, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('seat_limit', models.IntegerField()),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotmentapp.course_type')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotmentapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotmentapp.course'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_code', 'course_name'), name='unique_course_code_name'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('course', 'year', 'part'), name='unique_course_year_part'),
        ),
    ]
