# Generated by Django 4.2.11 on 2025-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotmentapp', '0003_student_first_sem_marks_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(default=2022),
        ),
    ]
