# Generated by Django 4.2.11 on 2025-07-20 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allotmentapp', '0010_alter_batch_options_batch_seats_taken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swapped_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('new_allotment1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_new1', to='allotmentapp.courseallotment')),
                ('new_allotment2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_new2', to='allotmentapp.courseallotment')),
                ('old_allotment1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_old1', to='allotmentapp.courseallotment')),
                ('old_allotment2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_old2', to='allotmentapp.courseallotment')),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_initiator', to='allotmentapp.student')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_recipient', to='allotmentapp.student')),
                ('swapped_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
