# Generated by Django 5.2.4 on 2025-07-28 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotmentapp', '0011_swaphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_sem_marks',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='normalized_marks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.DeleteModel(
            name='SwapHistory',
        ),
    ]
