# Generated by Django 5.2.4 on 2026-06-04 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotmentapp', '0012_alter_student_first_sem_marks_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseallotment',
            name='unique_student_paper_allotment',
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_sem_marks',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='First sem mark in percentage'),
        ),
    ]
